name: pluck_fleather
description: Clean, minimalistic and collaboration-ready rich text editor for Flutter.
version: 1.24.0+1
homepage: https://fleather-editor.github.io
repository: https://github.com/fleather-editor/fleather
issue_tracker: https://github.com/fleather-editor/fleather/issues
documentation: https://fleather-editor.github.io/docs/getting-started/quick-start/
screenshots:
  - description: "Fleather demo"
    path: images/screenshot.png
topics:
  - editor
  - text
  - wysiwyg
  - rich-text-editor
  - widgets

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: ^1.18.0
  parchment_delta: ^1.0.0
  parchment:
    git:
      url: https://github.com/Hamilton02/pluck-fleather.git
      ref: master
      path: packages/parchment

  intl: ">=0.19.0 <0.21.0"

dependency_overrides:
  parchment:
    path: ../parchment

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  fake_async: ^1.3.1
  mocktail: ^1.0.4
  meta: ^1.15.0

flutter:
  generate: true
